### ISSUE TITLE
Refreshing content

### ISSUE THREAD

**Issue by CMNatic** [tryhackmeltd/docs.tryhackme.com#60]
In preparation of incorporating the docs site with the bot, I'm going to go through the site and refresh the content before we begin pointing users more directly to it. Thought it would be best to raise as an issue before PR'ing because it'll be substantial. Will communicate the changes with other mentors & mods to get their thoughts and ideas.

Summary of pages being edited (26/06/2020):
**General** 
- [x]  Welcome to TryHackMe (has placeholder)
- [x]  TryHackMe Levels

**OpenVPN**
- [x]  Why do I need OpenVPN
- [x]  Installing OpenVPN
- [x]  Connecting with OpenVPN
- [x]  Troubleshooting

**Completing Rooms**
- [x]  Brief discussion of the differences between walkthrough and challenge rooms
- [x]  How Points Work (scoring)
- [x]  Room Difficulty Levels (placeholder)

**Sales and Billing**
- [x]  Formatting mainly
- [x] Corporate Enquiries

**Discord**
- [x]  Getting Started (Invite link, discussing the general topics of discussion)
- [x]  Verifying your level (Specifying the bot is now updated)

**API**
Szymex is working on formalising his notes to an external platform where examples of how the API works is better placed. Will reference to it when it's published.

**Comment by Kent55** [comment]
closed as appears complete! cheers @CMNatic

**Comment by CMNatic** [comment]
Thanks @Kent55 the docs site hasn't updated even though a PR's gone through, does it require a manual sync on your end? I know it's being retired but as the new KB has info from the docs, it'd be good to keep it up to date. At the least until it's officially retired ^^

**Comment by Kent55** [comment]
@CMNatic thanks for pointing this out, I noticed did notice this yesterday. All the deployment should be automated once the master branch successfully passes CI and security checks. I'll be pushing some new code soon which automates a lot of the documentation config, which solves the issue that was originally behind discussions to move away from docusaurus. Subsequently, I do believe this is going to remain as the official documentation site. I'll re-open this issue as there seems to be an issue with the automated deployment currently. Will close this again when the docs site has successfully been redeployed and the automation is fixed.

**Comment by Kent55** [comment]
Closing as deployment is now fixed

**Comment by CMNatic** [comment]
Thanks for your help @Kent55. If there are any other checks needed for development / submitting a PR, let me know and I'll make sure to consider and test them 👍

**Comment by Kent55** [comment]
Thanks, @CMNatic - so long as the automated checks pass in any PRs you raise. I check that anyway before approving them. This issue was unrelated (you didn't break anything), but generally, unless you modify any code you shouldn't have any problems. If you do modify code in future, just make sure you run `npm t` to run the test suite and make any changes to the spec files if any fail. Also, we use Snyk, which runs security scans on all PRs and branch builds, so it is possible for that to fail if dependencies are out of date on an old fork of the repo, so I recommend keeping your fork up to date with master, however, just updating the branch within the PR will merge changes from master to your branch and then automatically re-run Travis anyway. 

Really appreciate your contributions by the way, and feel free to ping me a message on Discord should you have any questions or issues.

**Comment by CMNatic** [comment]
Great, thanks @Kent55 I'll keep the above tests in mind. More or less what I expected and/or tested for so they sound more than reasonable!

Appreciate your help in keeping the documentation up-to-date (: Didn't realise you were in the THM Discord, I'll make sure to remember your offer and let you know of anything 👍
